export enum AutoUIViewPolicy {
    DEFAULT_AUTO_UI_POLICY_TYPE = -1,
    VIEW_POLICY_DEFAULT = 0,
    VIEW_POLICY_STRETCH = 1,
    VIEW_POLICY_AUTO_COLUMNS = 2,
    VIEW_POLICY_IGNORE = 3,
    VIEW_POLICY_TOP = 4,
    VIEW_POLICY_BOTTOM = 5,
    VIEW_POLICY_FLOAT = 6,
    VIEW_POLICY_TOP_PARENT = 7,
    VIEW_POLICY_MATCH_PARENT = 8,
    VIEW_POLICY_MATCH_PARENT_WIDTH = 9,
    VIEW_POLICY_MATCH_PARENT_HEIGHT = 10,
    VIEW_POLICY_WRAP_CONTENT = 11,
    VIEW_POLICY_WRAP_CONTENT_WIDTH = 12,
    VIEW_POLICY_WRAP_CONTENT_HEIGHT = 13,
    VIEW_POLICY_BITMAP_ORIGINAL_SPLIT = 14,
    VIEW_POLICY_KEEP_ORIGINAL_HEIGHT = 15,
    VIEW_POLICY_CENTER_ORIGINAL_SIZE = 16,
    VIEW_POLICY_BITMAP_AVERAGE_COLOR = 17,
    VIEW_POLICY_BITMAP_ORG = 18,
    VIEW_POLICY_ALL_CHILDREN_MATCH_SCREEN_WIDTH = 19
}

